import { useState, useEffect, useCallback } from 'react';
import { Link, useParams } from 'react-router-dom';
import { get, set } from '../../utils/storage';
import { SkeletonSidebar } from '../layout/Skeleton';

/**
 * Manifest types matching the content-manifest.json structure
 * generated by the Vite content plugin at build time.
 */
interface ManifestTopic {
  id: string;
  slug: string;
  title: string;
  source: 'parsed' | 'authored';
  sectionCount: number;
  wordCount: number;
  contentPath: string;
}

interface ManifestCategory {
  id: string;
  name: string;
  topics: ManifestTopic[];
}

interface ContentManifest {
  categories: ManifestCategory[];
  totalTopics: number;
  totalSections: number;
  buildTimestamp: string;
}

/** localStorage key for persisting expanded categories */
const NAV_STATE_KEY = 'nav-state';
/** localStorage key for progress (visited topics) */
const PROGRESS_KEY = 'progress';

interface NavState {
  expandedCategories: string[];
}

interface ProgressData {
  completedSections?: Record<string, string[]>;
  topicProgress?: Record<string, number>;
}

/**
 * Sidebar navigation component.
 * Renders the category tree from content-manifest.json with collapsible
 * categories, visited/unvisited indicators, and persisted expansion state.
 *
 * Requirements: 2.1, 2.6
 */
export function SidebarNavigation() {
  const [manifest, setManifest] = useState<ContentManifest | null>(null);
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());
  const [visitedTopics, setVisitedTopics] = useState<Set<string>>(new Set());
  const [error, setError] = useState<string | null>(null);

  const { categorySlug, topicSlug } = useParams<{
    categorySlug: string;
    topicSlug: string;
  }>();

  // Load content manifest on mount
  useEffect(() => {
    async function loadManifest() {
      try {
        const response = await fetch('/content-manifest.json');
        if (!response.ok) {
          throw new Error(`Failed to load manifest: ${response.status}`);
        }
        const data: ContentManifest = await response.json();
        setManifest(data);
      } catch (err) {
        // If manifest doesn't exist yet (dev mode), show empty state
        setError(err instanceof Error ? err.message : 'Failed to load navigation');
      }
    }
    loadManifest();
  }, []);

  // Load persisted nav state (expanded categories) from localStorage
  useEffect(() => {
    const navState = get<NavState>(NAV_STATE_KEY, { expandedCategories: [] });
    setExpandedCategories(new Set(navState.expandedCategories));
  }, []);

  // Load visited topics from progress state
  useEffect(() => {
    const progress = get<ProgressData>(PROGRESS_KEY, {});
    if (progress.topicProgress) {
      const visited = new Set<string>(
        Object.entries(progress.topicProgress)
          .filter(([, percentage]) => percentage > 0)
          .map(([topicId]) => topicId)
      );
      setVisitedTopics(visited);
    }
  }, []);

  // Persist expanded categories to localStorage whenever they change
  const persistExpandedState = useCallback((categories: Set<string>) => {
    const navState: NavState = { expandedCategories: Array.from(categories) };
    set(NAV_STATE_KEY, navState);
  }, []);

  const toggleCategory = useCallback((categoryId: string) => {
    setExpandedCategories((prev) => {
      const next = new Set(prev);
      if (next.has(categoryId)) {
        next.delete(categoryId);
      } else {
        next.add(categoryId);
      }
      persistExpandedState(next);
      return next;
    });
  }, [persistExpandedState]);

  const handleCategoryKeyDown = useCallback(
    (e: React.KeyboardEvent, categoryId: string) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        toggleCategory(categoryId);
      }
    },
    [toggleCategory]
  );

  if (error && !manifest) {
    return (
      <nav className="sidebar-nav" aria-label="Topic navigation">
        <p className="sidebar-empty">No content available yet.</p>
      </nav>
    );
  }

  if (!manifest) {
    return (
      <nav className="sidebar-nav" aria-label="Topic navigation">
        <SkeletonSidebar />
      </nav>
    );
  }

  return (
    <nav className="sidebar-nav" aria-label="Topic navigation">
      <div className="sidebar-quick-links">
        <Link to="/cheat-sheets" className="sidebar-quick-link">
          📋 All Cheat Sheets
        </Link>
      </div>
      <ul className="sidebar-category-list" role="tree">
        {manifest.categories.map((category) => {
          const isExpanded = expandedCategories.has(category.id);
          return (
            <li
              key={category.id}
              className="sidebar-category"
              role="treeitem"
              aria-expanded={isExpanded}
            >
              <button
                className="sidebar-category-toggle"
                onClick={() => toggleCategory(category.id)}
                onKeyDown={(e) => handleCategoryKeyDown(e, category.id)}
                aria-expanded={isExpanded}
                aria-controls={`category-topics-${category.id}`}
                type="button"
              >
                <span
                  className={`sidebar-category-chevron ${isExpanded ? 'expanded' : ''}`}
                  aria-hidden="true"
                >
                  ▶
                </span>
                <span className="sidebar-category-name">{category.name}</span>
                <span className="sidebar-category-count" aria-label={`${category.topics.length} topics`}>
                  {category.topics.length}
                </span>
              </button>

              {isExpanded && (
                <ul
                  className="sidebar-topic-list"
                  id={`category-topics-${category.id}`}
                  role="group"
                >
                  {category.topics.map((topic) => {
                    const isVisited = visitedTopics.has(topic.id);
                    const topicSlugPart = topic.slug.split('/')[1] ?? topic.id;
                    const isActive =
                      categorySlug === category.id && topicSlug === topicSlugPart;

                    return (
                      <li key={topic.id} className="sidebar-topic" role="treeitem">
                        <Link
                          to={`/topic/${category.id}/${topicSlugPart}`}
                          className={`sidebar-topic-link ${isActive ? 'active' : ''}`}
                          aria-current={isActive ? 'page' : undefined}
                        >
                          <span
                            className={`sidebar-topic-indicator ${isVisited ? 'visited' : 'unvisited'}`}
                            aria-label={isVisited ? 'Visited' : 'Not visited'}
                            title={isVisited ? 'Visited' : 'Not visited'}
                          >
                            {isVisited ? '✓' : '○'}
                          </span>
                          <span className="sidebar-topic-title">{topic.title}</span>
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              )}
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
