/**
 * Manifest types matching the content-manifest.json structure
 * generated by the Vite content plugin at build time.
 *
 * These types are the single source of truth for the manifest schema.
 * All components consuming the manifest should import from here.
 */

/** A subtopic entry within a multi-page topic */
export interface ManifestSubtopic {
  id: string;
  slug: string;
  title: string;
  wordCount: number;
}

/** A topic entry within a category */
export interface ManifestTopic {
  id: string;
  slug: string;
  title: string;
  source: 'parsed' | 'authored';
  sectionCount: number;
  wordCount: number;
  contentPath: string;
  subtopics?: ManifestSubtopic[];
}

/** A category grouping related topics */
export interface ManifestCategory {
  id: string;
  name: string;
  topics: ManifestTopic[];
}

/** The full content manifest structure */
export interface ContentManifest {
  categories: ManifestCategory[];
  totalTopics: number;
  totalSections: number;
  buildTimestamp: string;
}
