/**
 * Service Worker Registration Utility
 *
 * Registers the service worker generated by vite-plugin-pwa (Workbox).
 * Provides callbacks for update events and registration status.
 */

export interface SWRegistrationResult {
  registered: boolean;
  error?: string;
}

export interface SWUpdateEvent {
  type: 'update-available' | 'cache-complete' | 'cache-failed';
  message: string;
}

type SWUpdateCallback = (event: SWUpdateEvent) => void;

let updateCallback: SWUpdateCallback | null = null;

/**
 * Set a callback to be notified of service worker update events.
 */
export function onSWUpdate(callback: SWUpdateCallback): void {
  updateCallback = callback;
}

/**
 * Register the service worker.
 * Returns a result indicating success or failure.
 */
export async function registerServiceWorker(): Promise<SWRegistrationResult> {
  if (!('serviceWorker' in navigator)) {
    return { registered: false, error: 'Service workers not supported' };
  }

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });

    // Listen for updates
    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing;
      if (!newWorker) return;

      newWorker.addEventListener('statechange', () => {
        if (newWorker.state === 'installed') {
          if (navigator.serviceWorker.controller) {
            // New content available, notify the app
            updateCallback?.({
              type: 'update-available',
              message: 'New content is available. Refresh to update.',
            });
          } else {
            // Content cached for offline use
            updateCallback?.({
              type: 'cache-complete',
              message: 'Content is cached for offline use.',
            });
          }
        }
      });
    });

    // Handle controller change (when skipWaiting is called)
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      // The new service worker has taken control
    });

    return { registered: true };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    updateCallback?.({
      type: 'cache-failed',
      message: 'Offline access is unavailable.',
    });
    return { registered: false, error: errorMessage };
  }
}
